name: Checks # Workflow name

on:
  pull_request:
    types: [opened, synchronize] # Workflow triggering events

jobs: # A workflow can have multiple jobs
  checks: # Name of the job
    runs-on: ubuntu-latest # Instance type where job will run

    steps:
    - name: "Checkout" # Download code from the repository
      uses: actions/checkout@v2 # Public action
      with:
        fetch-depth: 0 # Checkout all branches and tags

    - name: "Use NodeJS 14" # Setup node using version 14
      uses: actions/setup-node@v2 # Public action
      with: 
        node-version: '14'

   - name: "Setup npm" # Add our registry to npm config
      run: | # Custom action
        npm set @mitchallen:registry=https://npm.pkg.github.com/mitchallen
        npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

   - name: Install dependencies
      run: | # Install and link dependencies
        npm ci
        npx lerna bootstrap