name: Checks 
run-name: Checks by ${{ github.actor }}

on:
  pull_request:
    types: [opened, synchronize] 

jobs:
  checks: 
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout" 
      uses: actions/checkout@v4 
      with:
        fetch-depth: 0 

    - name: "Use NodeJS 16" 
      uses: actions/setup-node@v4 
      with: 
        node-version: '18'

    - name: "Setup npm" 
      run: | 
        npm set @${{ github.actor }}:registry=https://npm.pkg.github.com/${{ github.actor }}
        npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

    - name: Install dependencies
      run: | 
        npm install 

    - name: Run tests
      run: | 
        npx lerna run test